// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/calypr/data-client/data-client/jwt (interfaces: ConfigureInterface)

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	jwt "github.com/calypr/data-client/data-client/jwt"
	url "net/url"
	reflect "reflect"
)

// MockConfigureInterface is a mock of ConfigureInterface interface
type MockConfigureInterface struct {
	ctrl     *gomock.Controller
	recorder *MockConfigureInterfaceMockRecorder
}

// MockConfigureInterfaceMockRecorder is the mock recorder for MockConfigureInterface
type MockConfigureInterfaceMockRecorder struct {
	mock *MockConfigureInterface
}

// NewMockConfigureInterface creates a new mock instance
func NewMockConfigureInterface(ctrl *gomock.Controller) *MockConfigureInterface {
	mock := &MockConfigureInterface{ctrl: ctrl}
	mock.recorder = &MockConfigureInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockConfigureInterface) EXPECT() *MockConfigureInterfaceMockRecorder {
	return m.recorder
}

// GetConfigPath mocks base method
func (m *MockConfigureInterface) GetConfigPath() (string, error) {
	ret := m.ctrl.Call(m, "GetConfigPath")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfigPath indicates an expected call of GetConfigPath
func (mr *MockConfigureInterfaceMockRecorder) GetConfigPath() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfigPath", reflect.TypeOf((*MockConfigureInterface)(nil).GetConfigPath))
}

// ParseConfig mocks base method
func (m *MockConfigureInterface) ParseConfig(arg0 string) (jwt.Credential, error) {
	ret := m.ctrl.Call(m, "ParseConfig", arg0)
	ret0, _ := ret[0].(jwt.Credential)
	return ret0, nil
}

// ParseConfig indicates an expected call of ParseConfig
func (mr *MockConfigureInterfaceMockRecorder) ParseConfig(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseConfig", reflect.TypeOf((*MockConfigureInterface)(nil).ParseConfig), arg0)
}

// ParseKeyValue mocks base method
func (m *MockConfigureInterface) ParseKeyValue(arg0, arg1 string) (string, error) {
	ret := m.ctrl.Call(m, "ParseKeyValue", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseKeyValue indicates an expected call of ParseKeyValue
func (mr *MockConfigureInterfaceMockRecorder) ParseKeyValue(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseKeyValue", reflect.TypeOf((*MockConfigureInterface)(nil).ParseKeyValue), arg0, arg1)
}

// ReadFile mocks base method
func (m *MockConfigureInterface) ReadFile(arg0, arg1 string) string {
	ret := m.ctrl.Call(m, "ReadFile", arg0, arg1)
	ret0, _ := ret[0].(string)
	return ret0
}

// ReadFile indicates an expected call of ReadFile
func (mr *MockConfigureInterfaceMockRecorder) ReadFile(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFile", reflect.TypeOf((*MockConfigureInterface)(nil).ReadFile), arg0, arg1)
}

// UpdateConfigFile mocks base method
func (m *MockConfigureInterface) UpdateConfigFile(arg0 jwt.Credential) error {
	m.ctrl.Call(m, "UpdateConfigFile", arg0)
	return nil
}

// UpdateConfigFile indicates an expected call of UpdateConfigFile
func (mr *MockConfigureInterfaceMockRecorder) UpdateConfigFile(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateConfigFile", reflect.TypeOf((*MockConfigureInterface)(nil).UpdateConfigFile), arg0)
}

// ValidateUrl mocks base method
func (m *MockConfigureInterface) ValidateUrl(arg0 string) (*url.URL, error) {
	ret := m.ctrl.Call(m, "ValidateUrl", arg0)
	ret0, _ := ret[0].(*url.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateUrl indicates an expected call of ValidateUrl
func (mr *MockConfigureInterfaceMockRecorder) ValidateUrl(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateUrl", reflect.TypeOf((*MockConfigureInterface)(nil).ValidateUrl), arg0)
}
