// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/calypr/gen3-client/gen3-client/jwt (interfaces: RequestInterface)

// Package mocks is a generated GoMock package.
package mocks

import (
	bytes "bytes"
	gomock "github.com/golang/mock/gomock"
	jwt "github.com/calypr/gen3-client/gen3-client/jwt"
	http "net/http"
	reflect "reflect"
)

// MockRequestInterface is a mock of RequestInterface interface
type MockRequestInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRequestInterfaceMockRecorder
}

// MockRequestInterfaceMockRecorder is the mock recorder for MockRequestInterface
type MockRequestInterfaceMockRecorder struct {
	mock *MockRequestInterface
}

// NewMockRequestInterface creates a new mock instance
func NewMockRequestInterface(ctrl *gomock.Controller) *MockRequestInterface {
	mock := &MockRequestInterface{ctrl: ctrl}
	mock.recorder = &MockRequestInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRequestInterface) EXPECT() *MockRequestInterfaceMockRecorder {
	return m.recorder
}

// MakeARequest mocks base method
func (m *MockRequestInterface) MakeARequest(arg0, arg1, arg2, arg3 string, arg4 map[string]string, arg5 *bytes.Buffer, arg6 bool) (*http.Response, error) {
	ret := m.ctrl.Call(m, "MakeARequest", arg0, arg1, arg2, arg3, arg4, arg5, arg6)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MakeARequest indicates an expected call of MakeARequest
func (mr *MockRequestInterfaceMockRecorder) MakeARequest(arg0, arg1, arg2, arg3, arg4, arg5, arg6 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeARequest", reflect.TypeOf((*MockRequestInterface)(nil).MakeARequest), arg0, arg1, arg2, arg3, arg4, arg5, arg6)
}

// RequestNewAccessToken mocks base method
func (m *MockRequestInterface) RequestNewAccessToken(arg0 string, arg1 *jwt.Credential) error {
	ret := m.ctrl.Call(m, "RequestNewAccessToken", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// RequestNewAccessToken indicates an expected call of RequestNewAccessToken
func (mr *MockRequestInterfaceMockRecorder) RequestNewAccessToken(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestNewAccessToken", reflect.TypeOf((*MockRequestInterface)(nil).RequestNewAccessToken), arg0, arg1)
}
