// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/uc-cdis/cdis-data-client/jwt (interfaces: ConfigureInterface)

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	jwt "github.com/uc-cdis/cdis-data-client/jwt"
	reflect "reflect"
)

// MockConfigureInterface is a mock of ConfigureInterface interface
type MockConfigureInterface struct {
	ctrl     *gomock.Controller
	recorder *MockConfigureInterfaceMockRecorder
}

// MockConfigureInterfaceMockRecorder is the mock recorder for MockConfigureInterface
type MockConfigureInterfaceMockRecorder struct {
	mock *MockConfigureInterface
}

// NewMockConfigureInterface creates a new mock instance
func NewMockConfigureInterface(ctrl *gomock.Controller) *MockConfigureInterface {
	mock := &MockConfigureInterface{ctrl: ctrl}
	mock.recorder = &MockConfigureInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockConfigureInterface) EXPECT() *MockConfigureInterfaceMockRecorder {
	return m.recorder
}

// ParseUrl mocks base method
func (m *MockConfigureInterface) ParseUrl() string {
	ret := m.ctrl.Call(m, "ParseUrl")
	ret0, _ := ret[0].(string)
	return ret0
}

// ParseUrl indicates an expected call of ParseUrl
func (mr *MockConfigureInterfaceMockRecorder) ParseUrl() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseUrl", reflect.TypeOf((*MockConfigureInterface)(nil).ParseUrl))
}

// ReadCredentials mocks base method
func (m *MockConfigureInterface) ReadCredentials(arg0 string) jwt.Credential {
	ret := m.ctrl.Call(m, "ReadCredentials", arg0)
	ret0, _ := ret[0].(jwt.Credential)
	return ret0
}

// ReadCredentials indicates an expected call of ReadCredentials
func (mr *MockConfigureInterfaceMockRecorder) ReadCredentials(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadCredentials", reflect.TypeOf((*MockConfigureInterface)(nil).ReadCredentials), arg0)
}

// ReadFile mocks base method
func (m *MockConfigureInterface) ReadFile(arg0, arg1 string) string {
	ret := m.ctrl.Call(m, "ReadFile", arg0, arg1)
	ret0, _ := ret[0].(string)
	return ret0
}

// ReadFile indicates an expected call of ReadFile
func (mr *MockConfigureInterfaceMockRecorder) ReadFile(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFile", reflect.TypeOf((*MockConfigureInterface)(nil).ReadFile), arg0, arg1)
}

// ReadLines mocks base method
func (m *MockConfigureInterface) ReadLines(arg0 jwt.Credential, arg1 []byte, arg2, arg3 string) ([]string, bool) {
	ret := m.ctrl.Call(m, "ReadLines", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// ReadLines indicates an expected call of ReadLines
func (mr *MockConfigureInterfaceMockRecorder) ReadLines(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadLines", reflect.TypeOf((*MockConfigureInterface)(nil).ReadLines), arg0, arg1, arg2, arg3)
}

// TestMock mocks base method
func (m *MockConfigureInterface) TestMock() bool {
	ret := m.ctrl.Call(m, "TestMock")
	ret0, _ := ret[0].(bool)
	return ret0
}

// TestMock indicates an expected call of TestMock
func (mr *MockConfigureInterfaceMockRecorder) TestMock() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TestMock", reflect.TypeOf((*MockConfigureInterface)(nil).TestMock))
}

// UpdateConfigFile mocks base method
func (m *MockConfigureInterface) UpdateConfigFile(arg0 jwt.Credential, arg1 []byte, arg2, arg3, arg4 string) {
	m.ctrl.Call(m, "UpdateConfigFile", arg0, arg1, arg2, arg3, arg4)
}

// UpdateConfigFile indicates an expected call of UpdateConfigFile
func (mr *MockConfigureInterfaceMockRecorder) UpdateConfigFile(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateConfigFile", reflect.TypeOf((*MockConfigureInterface)(nil).UpdateConfigFile), arg0, arg1, arg2, arg3, arg4)
}
